// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/contract/exchange_contract.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExchangeCreateContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	FirstTokenId         []byte   `protobuf:"bytes,2,opt,name=first_token_id,json=firstTokenId,proto3" json:"first_token_id,omitempty"`
	FirstTokenBalance    int64    `protobuf:"varint,3,opt,name=first_token_balance,json=firstTokenBalance,proto3" json:"first_token_balance,omitempty"`
	SecondTokenId        []byte   `protobuf:"bytes,4,opt,name=second_token_id,json=secondTokenId,proto3" json:"second_token_id,omitempty"`
	SecondTokenBalance   int64    `protobuf:"varint,5,opt,name=second_token_balance,json=secondTokenBalance,proto3" json:"second_token_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeCreateContract) Reset()         { *m = ExchangeCreateContract{} }
func (m *ExchangeCreateContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeCreateContract) ProtoMessage()    {}
func (*ExchangeCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c7f776bef66f61, []int{0}
}

func (m *ExchangeCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeCreateContract.Unmarshal(m, b)
}
func (m *ExchangeCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeCreateContract.Marshal(b, m, deterministic)
}
func (m *ExchangeCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeCreateContract.Merge(m, src)
}
func (m *ExchangeCreateContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeCreateContract.Size(m)
}
func (m *ExchangeCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeCreateContract proto.InternalMessageInfo

func (m *ExchangeCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeCreateContract) GetFirstTokenId() []byte {
	if m != nil {
		return m.FirstTokenId
	}
	return nil
}

func (m *ExchangeCreateContract) GetFirstTokenBalance() int64 {
	if m != nil {
		return m.FirstTokenBalance
	}
	return 0
}

func (m *ExchangeCreateContract) GetSecondTokenId() []byte {
	if m != nil {
		return m.SecondTokenId
	}
	return nil
}

func (m *ExchangeCreateContract) GetSecondTokenBalance() int64 {
	if m != nil {
		return m.SecondTokenBalance
	}
	return 0
}

type ExchangeInjectContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeInjectContract) Reset()         { *m = ExchangeInjectContract{} }
func (m *ExchangeInjectContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeInjectContract) ProtoMessage()    {}
func (*ExchangeInjectContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c7f776bef66f61, []int{1}
}

func (m *ExchangeInjectContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeInjectContract.Unmarshal(m, b)
}
func (m *ExchangeInjectContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeInjectContract.Marshal(b, m, deterministic)
}
func (m *ExchangeInjectContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeInjectContract.Merge(m, src)
}
func (m *ExchangeInjectContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeInjectContract.Size(m)
}
func (m *ExchangeInjectContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeInjectContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeInjectContract proto.InternalMessageInfo

func (m *ExchangeInjectContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeInjectContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeInjectContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeInjectContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type ExchangeWithdrawContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeWithdrawContract) Reset()         { *m = ExchangeWithdrawContract{} }
func (m *ExchangeWithdrawContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeWithdrawContract) ProtoMessage()    {}
func (*ExchangeWithdrawContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c7f776bef66f61, []int{2}
}

func (m *ExchangeWithdrawContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeWithdrawContract.Unmarshal(m, b)
}
func (m *ExchangeWithdrawContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeWithdrawContract.Marshal(b, m, deterministic)
}
func (m *ExchangeWithdrawContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeWithdrawContract.Merge(m, src)
}
func (m *ExchangeWithdrawContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeWithdrawContract.Size(m)
}
func (m *ExchangeWithdrawContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeWithdrawContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeWithdrawContract proto.InternalMessageInfo

func (m *ExchangeWithdrawContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeWithdrawContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeWithdrawContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeWithdrawContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type ExchangeTransactionContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	Expected             int64    `protobuf:"varint,5,opt,name=expected,proto3" json:"expected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeTransactionContract) Reset()         { *m = ExchangeTransactionContract{} }
func (m *ExchangeTransactionContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeTransactionContract) ProtoMessage()    {}
func (*ExchangeTransactionContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c7f776bef66f61, []int{3}
}

func (m *ExchangeTransactionContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeTransactionContract.Unmarshal(m, b)
}
func (m *ExchangeTransactionContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeTransactionContract.Marshal(b, m, deterministic)
}
func (m *ExchangeTransactionContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeTransactionContract.Merge(m, src)
}
func (m *ExchangeTransactionContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeTransactionContract.Size(m)
}
func (m *ExchangeTransactionContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeTransactionContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeTransactionContract proto.InternalMessageInfo

func (m *ExchangeTransactionContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeTransactionContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeTransactionContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeTransactionContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

func (m *ExchangeTransactionContract) GetExpected() int64 {
	if m != nil {
		return m.Expected
	}
	return 0
}

func init() {
	proto.RegisterType((*ExchangeCreateContract)(nil), "protocol.ExchangeCreateContract")
	proto.RegisterType((*ExchangeInjectContract)(nil), "protocol.ExchangeInjectContract")
	proto.RegisterType((*ExchangeWithdrawContract)(nil), "protocol.ExchangeWithdrawContract")
	proto.RegisterType((*ExchangeTransactionContract)(nil), "protocol.ExchangeTransactionContract")
}

func init() {
	proto.RegisterFile("core/contract/exchange_contract.proto", fileDescriptor_10c7f776bef66f61)
}

var fileDescriptor_10c7f776bef66f61 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xd3, 0xdb, 0xcb, 0xbd, 0xe4, 0x5c, 0xb8, 0xc6, 0x91, 0x98, 0xaa, 0x0b, 0x09, 0xfe,
	0x63, 0x43, 0x8b, 0xf1, 0x09, 0x84, 0xb8, 0x60, 0xdb, 0x90, 0x98, 0xb8, 0x69, 0x86, 0x99, 0x43,
	0xa9, 0xe2, 0x0c, 0x4e, 0x0f, 0x01, 0x9f, 0xc2, 0xf8, 0x26, 0xbe, 0x98, 0xef, 0x60, 0x98, 0x76,
	0x00, 0x97, 0xae, 0x58, 0x35, 0xe7, 0xeb, 0xaf, 0x5f, 0xbe, 0xaf, 0x73, 0x06, 0x2e, 0x84, 0x36,
	0x18, 0x09, 0xad, 0xc8, 0x70, 0x41, 0x11, 0x2e, 0xc5, 0x84, 0xab, 0x14, 0x13, 0xa7, 0x84, 0x33,
	0xa3, 0x49, 0xb3, 0xaa, 0x7d, 0x08, 0x3d, 0x6d, 0x7d, 0x7a, 0x70, 0x78, 0x57, 0x52, 0x7d, 0x83,
	0x9c, 0xb0, 0x5f, 0xa2, 0xec, 0x0c, 0xea, 0x7a, 0xa1, 0xd0, 0x24, 0x5c, 0x4a, 0x83, 0x79, 0x1e,
	0x78, 0x4d, 0xaf, 0x5d, 0x8b, 0x6b, 0x56, 0xbc, 0x2d, 0x34, 0x76, 0x0e, 0xff, 0xc7, 0x99, 0xc9,
	0x29, 0x21, 0xfd, 0x84, 0x2a, 0xc9, 0x64, 0xf0, 0xab, 0xa0, 0xac, 0x3a, 0x5c, 0x89, 0x03, 0xc9,
	0x42, 0x38, 0xd8, 0xa6, 0x46, 0x7c, 0xca, 0x95, 0xc0, 0xc0, 0x6f, 0x7a, 0x6d, 0x3f, 0xde, 0xdf,
	0xa0, 0xbd, 0xe2, 0x05, 0xbb, 0x84, 0xbd, 0x1c, 0x85, 0x56, 0x72, 0x63, 0xfb, 0xdb, 0xda, 0xd6,
	0x0b, 0xd9, 0xf9, 0x76, 0xa1, 0xf1, 0x8d, 0x73, 0xc6, 0x15, 0x6b, 0xcc, 0xb6, 0xe0, 0xd2, 0xb9,
	0xf5, 0xb6, 0xd5, 0x77, 0xa0, 0x1e, 0x51, 0xd0, 0xcf, 0xfa, 0x9e, 0xc2, 0xbf, 0xf5, 0x4f, 0x2d,
	0xcb, 0xfa, 0x31, 0x38, 0x69, 0x20, 0xd9, 0x11, 0x54, 0xd7, 0x99, 0x7d, 0x6b, 0xf0, 0x97, 0xca,
	0xb4, 0x0d, 0xa8, 0xbc, 0xcc, 0xb9, 0x22, 0xdb, 0xc5, 0x8f, 0x8b, 0xa1, 0xf5, 0xee, 0x41, 0xe0,
	0x12, 0xdd, 0x67, 0x34, 0x91, 0x86, 0x2f, 0x76, 0x9d, 0xe9, 0xc3, 0x83, 0x13, 0x97, 0x69, 0x68,
	0xb8, 0xca, 0xb9, 0xa0, 0x4c, 0xab, 0x1d, 0xc7, 0x62, 0xc7, 0x50, 0xc5, 0xe5, 0x0c, 0x05, 0xa1,
	0x2c, 0x8f, 0x78, 0x3d, 0xf7, 0xfa, 0x10, 0x68, 0x93, 0x86, 0x64, 0xb4, 0x2a, 0x96, 0x3c, 0x0f,
	0xdd, 0xd2, 0x3f, 0x5c, 0xa5, 0x19, 0x4d, 0xe6, 0xa3, 0x50, 0xe8, 0xe7, 0xa8, 0xbb, 0xbc, 0xee,
	0x8e, 0xa3, 0x15, 0xd6, 0x49, 0xcd, 0x4c, 0x74, 0x52, 0x4e, 0xb8, 0xe0, 0xaf, 0xd1, 0xea, 0xe2,
	0x8c, 0xfe, 0xd8, 0x2f, 0x6f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xff, 0xe5, 0xba, 0x47,
	0x03, 0x00, 0x00,
}
