// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/contract/proposal_contract.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProposalApproveContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ProposalId           int64    `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	IsAddApproval        bool     `protobuf:"varint,3,opt,name=is_add_approval,json=isAddApproval,proto3" json:"is_add_approval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalApproveContract) Reset()         { *m = ProposalApproveContract{} }
func (m *ProposalApproveContract) String() string { return proto.CompactTextString(m) }
func (*ProposalApproveContract) ProtoMessage()    {}
func (*ProposalApproveContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b339c1bd781d6d14, []int{0}
}

func (m *ProposalApproveContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalApproveContract.Unmarshal(m, b)
}
func (m *ProposalApproveContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalApproveContract.Marshal(b, m, deterministic)
}
func (m *ProposalApproveContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalApproveContract.Merge(m, src)
}
func (m *ProposalApproveContract) XXX_Size() int {
	return xxx_messageInfo_ProposalApproveContract.Size(m)
}
func (m *ProposalApproveContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalApproveContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalApproveContract proto.InternalMessageInfo

func (m *ProposalApproveContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalApproveContract) GetProposalId() int64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *ProposalApproveContract) GetIsAddApproval() bool {
	if m != nil {
		return m.IsAddApproval
	}
	return false
}

type ProposalCreateContract struct {
	OwnerAddress         []byte          `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Parameters           map[int64]int64 `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProposalCreateContract) Reset()         { *m = ProposalCreateContract{} }
func (m *ProposalCreateContract) String() string { return proto.CompactTextString(m) }
func (*ProposalCreateContract) ProtoMessage()    {}
func (*ProposalCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b339c1bd781d6d14, []int{1}
}

func (m *ProposalCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalCreateContract.Unmarshal(m, b)
}
func (m *ProposalCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalCreateContract.Marshal(b, m, deterministic)
}
func (m *ProposalCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalCreateContract.Merge(m, src)
}
func (m *ProposalCreateContract) XXX_Size() int {
	return xxx_messageInfo_ProposalCreateContract.Size(m)
}
func (m *ProposalCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalCreateContract proto.InternalMessageInfo

func (m *ProposalCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalCreateContract) GetParameters() map[int64]int64 {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ProposalDeleteContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ProposalId           int64    `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalDeleteContract) Reset()         { *m = ProposalDeleteContract{} }
func (m *ProposalDeleteContract) String() string { return proto.CompactTextString(m) }
func (*ProposalDeleteContract) ProtoMessage()    {}
func (*ProposalDeleteContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_b339c1bd781d6d14, []int{2}
}

func (m *ProposalDeleteContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalDeleteContract.Unmarshal(m, b)
}
func (m *ProposalDeleteContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalDeleteContract.Marshal(b, m, deterministic)
}
func (m *ProposalDeleteContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalDeleteContract.Merge(m, src)
}
func (m *ProposalDeleteContract) XXX_Size() int {
	return xxx_messageInfo_ProposalDeleteContract.Size(m)
}
func (m *ProposalDeleteContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalDeleteContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalDeleteContract proto.InternalMessageInfo

func (m *ProposalDeleteContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalDeleteContract) GetProposalId() int64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func init() {
	proto.RegisterType((*ProposalApproveContract)(nil), "protocol.ProposalApproveContract")
	proto.RegisterType((*ProposalCreateContract)(nil), "protocol.ProposalCreateContract")
	proto.RegisterMapType((map[int64]int64)(nil), "protocol.ProposalCreateContract.ParametersEntry")
	proto.RegisterType((*ProposalDeleteContract)(nil), "protocol.ProposalDeleteContract")
}

func init() {
	proto.RegisterFile("core/contract/proposal_contract.proto", fileDescriptor_b339c1bd781d6d14)
}

var fileDescriptor_b339c1bd781d6d14 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0x86, 0xff, 0x9f, 0x32, 0x6d, 0xa9, 0x04, 0xd1, 0xe0, 0xc5, 0x50, 0x51, 0x73,
	0xe9, 0xa6, 0xea, 0x45, 0x04, 0x0f, 0xb1, 0x7a, 0xf0, 0x56, 0x72, 0xf4, 0x60, 0xd9, 0x66, 0xd7,
	0x18, 0x4c, 0x33, 0xcb, 0xec, 0xb6, 0xb5, 0x4f, 0xe0, 0xdb, 0xf9, 0x4c, 0x92, 0x34, 0xa9, 0x22,
	0x5e, 0x04, 0x4f, 0xc9, 0xfe, 0xf6, 0x9b, 0x6f, 0xe6, 0xdb, 0x5d, 0x38, 0x4e, 0x90, 0x54, 0x98,
	0x60, 0x61, 0x49, 0x24, 0x36, 0xd4, 0x84, 0x1a, 0x8d, 0xc8, 0xa7, 0x0d, 0xe1, 0x9a, 0xd0, 0xa2,
	0xdb, 0xae, 0x3e, 0x09, 0xe6, 0x83, 0x37, 0x06, 0xfb, 0x93, 0x5a, 0x15, 0x69, 0x4d, 0xb8, 0x54,
	0xe3, 0x5a, 0xeb, 0x1e, 0x41, 0x0f, 0x57, 0x85, 0xa2, 0xa9, 0x90, 0x92, 0x94, 0x31, 0x1e, 0xf3,
	0x59, 0xd0, 0x8d, 0xbb, 0x15, 0x8c, 0x36, 0xcc, 0x3d, 0x84, 0xce, 0xb6, 0x4b, 0x26, 0xbd, 0x96,
	0xcf, 0x02, 0x27, 0x86, 0x06, 0xdd, 0x4b, 0xf7, 0x04, 0xfa, 0x99, 0x29, 0x2d, 0xa6, 0xa2, 0xf2,
	0x17, 0xb9, 0xe7, 0xf8, 0x2c, 0x68, 0xc7, 0xbd, 0xcc, 0x44, 0x52, 0x46, 0x35, 0x1c, 0xbc, 0x33,
	0xd8, 0x6b, 0x26, 0x19, 0x93, 0x12, 0xf6, 0x97, 0x83, 0x4c, 0x00, 0xb4, 0x20, 0x31, 0x57, 0x56,
	0x91, 0xf1, 0x5a, 0xbe, 0x13, 0x74, 0xce, 0x47, 0xbc, 0x09, 0xca, 0x7f, 0xb6, 0xe6, 0x93, 0x6d,
	0xc9, 0x5d, 0x61, 0x69, 0x1d, 0x7f, 0xf1, 0x38, 0xb8, 0x86, 0xfe, 0xb7, 0x6d, 0x77, 0x07, 0x9c,
	0x17, 0xb5, 0xae, 0xfa, 0x3b, 0x71, 0xf9, 0xeb, 0xee, 0xc2, 0xbf, 0xa5, 0xc8, 0x17, 0xaa, 0x4e,
	0xbe, 0x59, 0x5c, 0xb5, 0x2e, 0xd9, 0xe0, 0xf1, 0x33, 0xcf, 0xad, 0xca, 0x95, 0xfd, 0xe3, 0x83,
	0xbd, 0x19, 0x83, 0x87, 0x94, 0x72, 0x4b, 0x58, 0x6c, 0x62, 0x1a, 0xde, 0x5c, 0xf3, 0xc3, 0x69,
	0x9a, 0xd9, 0xe7, 0xc5, 0x8c, 0x27, 0x38, 0x0f, 0x47, 0xaf, 0x67, 0xa3, 0xa7, 0xb0, 0x94, 0x0d,
	0x53, 0xd2, 0xc9, 0x30, 0x15, 0x56, 0xad, 0xc4, 0x3a, 0x2c, 0x9f, 0xca, 0xec, 0x7f, 0x55, 0x79,
	0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0x88, 0x8a, 0x2e, 0x88, 0x39, 0x02, 0x00, 0x00,
}
