// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/contract/smart_contract.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SmartContract_ABI_Entry_EntryType int32

const (
	SmartContract_ABI_Entry_UnknownEntryType SmartContract_ABI_Entry_EntryType = 0
	SmartContract_ABI_Entry_Constructor      SmartContract_ABI_Entry_EntryType = 1
	SmartContract_ABI_Entry_Function         SmartContract_ABI_Entry_EntryType = 2
	SmartContract_ABI_Entry_Event            SmartContract_ABI_Entry_EntryType = 3
	SmartContract_ABI_Entry_Fallback         SmartContract_ABI_Entry_EntryType = 4
)

var SmartContract_ABI_Entry_EntryType_name = map[int32]string{
	0: "UnknownEntryType",
	1: "Constructor",
	2: "Function",
	3: "Event",
	4: "Fallback",
}

var SmartContract_ABI_Entry_EntryType_value = map[string]int32{
	"UnknownEntryType": 0,
	"Constructor":      1,
	"Function":         2,
	"Event":            3,
	"Fallback":         4,
}

func (x SmartContract_ABI_Entry_EntryType) String() string {
	return proto.EnumName(SmartContract_ABI_Entry_EntryType_name, int32(x))
}

func (SmartContract_ABI_Entry_EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0, 0, 0, 0}
}

type SmartContract_ABI_Entry_StateMutabilityType int32

const (
	SmartContract_ABI_Entry_UnknownMutabilityType SmartContract_ABI_Entry_StateMutabilityType = 0
	SmartContract_ABI_Entry_Pure                  SmartContract_ABI_Entry_StateMutabilityType = 1
	SmartContract_ABI_Entry_View                  SmartContract_ABI_Entry_StateMutabilityType = 2
	SmartContract_ABI_Entry_Nonpayable            SmartContract_ABI_Entry_StateMutabilityType = 3
	SmartContract_ABI_Entry_Payable               SmartContract_ABI_Entry_StateMutabilityType = 4
)

var SmartContract_ABI_Entry_StateMutabilityType_name = map[int32]string{
	0: "UnknownMutabilityType",
	1: "Pure",
	2: "View",
	3: "Nonpayable",
	4: "Payable",
}

var SmartContract_ABI_Entry_StateMutabilityType_value = map[string]int32{
	"UnknownMutabilityType": 0,
	"Pure":                  1,
	"View":                  2,
	"Nonpayable":            3,
	"Payable":               4,
}

func (x SmartContract_ABI_Entry_StateMutabilityType) String() string {
	return proto.EnumName(SmartContract_ABI_Entry_StateMutabilityType_name, int32(x))
}

func (SmartContract_ABI_Entry_StateMutabilityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0, 0, 0, 1}
}

type SmartContract struct {
	OriginAddress              []byte             `protobuf:"bytes,1,opt,name=origin_address,json=originAddress,proto3" json:"origin_address,omitempty"`
	ContractAddress            []byte             `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Abi                        *SmartContract_ABI `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`
	Bytecode                   []byte             `protobuf:"bytes,4,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	CallValue                  int64              `protobuf:"varint,5,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	ConsumeUserResourcePercent int64              `protobuf:"varint,6,opt,name=consume_user_resource_percent,json=consumeUserResourcePercent,proto3" json:"consume_user_resource_percent,omitempty"`
	Name                       string             `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	OriginEnergyLimit          int64              `protobuf:"varint,8,opt,name=origin_energy_limit,json=originEnergyLimit,proto3" json:"origin_energy_limit,omitempty"`
	CodeHash                   []byte             `protobuf:"bytes,9,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	TrxHash                    []byte             `protobuf:"bytes,10,opt,name=trx_hash,json=trxHash,proto3" json:"trx_hash,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}           `json:"-"`
	XXX_unrecognized           []byte             `json:"-"`
	XXX_sizecache              int32              `json:"-"`
}

func (m *SmartContract) Reset()         { *m = SmartContract{} }
func (m *SmartContract) String() string { return proto.CompactTextString(m) }
func (*SmartContract) ProtoMessage()    {}
func (*SmartContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0}
}

func (m *SmartContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContract.Unmarshal(m, b)
}
func (m *SmartContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContract.Marshal(b, m, deterministic)
}
func (m *SmartContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContract.Merge(m, src)
}
func (m *SmartContract) XXX_Size() int {
	return xxx_messageInfo_SmartContract.Size(m)
}
func (m *SmartContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContract.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContract proto.InternalMessageInfo

func (m *SmartContract) GetOriginAddress() []byte {
	if m != nil {
		return m.OriginAddress
	}
	return nil
}

func (m *SmartContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *SmartContract) GetAbi() *SmartContract_ABI {
	if m != nil {
		return m.Abi
	}
	return nil
}

func (m *SmartContract) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

func (m *SmartContract) GetCallValue() int64 {
	if m != nil {
		return m.CallValue
	}
	return 0
}

func (m *SmartContract) GetConsumeUserResourcePercent() int64 {
	if m != nil {
		return m.ConsumeUserResourcePercent
	}
	return 0
}

func (m *SmartContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartContract) GetOriginEnergyLimit() int64 {
	if m != nil {
		return m.OriginEnergyLimit
	}
	return 0
}

func (m *SmartContract) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *SmartContract) GetTrxHash() []byte {
	if m != nil {
		return m.TrxHash
	}
	return nil
}

type SmartContract_ABI struct {
	Entrys               []*SmartContract_ABI_Entry `protobuf:"bytes,1,rep,name=entrys,proto3" json:"entrys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SmartContract_ABI) Reset()         { *m = SmartContract_ABI{} }
func (m *SmartContract_ABI) String() string { return proto.CompactTextString(m) }
func (*SmartContract_ABI) ProtoMessage()    {}
func (*SmartContract_ABI) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0, 0}
}

func (m *SmartContract_ABI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContract_ABI.Unmarshal(m, b)
}
func (m *SmartContract_ABI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContract_ABI.Marshal(b, m, deterministic)
}
func (m *SmartContract_ABI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContract_ABI.Merge(m, src)
}
func (m *SmartContract_ABI) XXX_Size() int {
	return xxx_messageInfo_SmartContract_ABI.Size(m)
}
func (m *SmartContract_ABI) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContract_ABI.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContract_ABI proto.InternalMessageInfo

func (m *SmartContract_ABI) GetEntrys() []*SmartContract_ABI_Entry {
	if m != nil {
		return m.Entrys
	}
	return nil
}

type SmartContract_ABI_Entry struct {
	Anonymous            bool                                        `protobuf:"varint,1,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	Constant             bool                                        `protobuf:"varint,2,opt,name=constant,proto3" json:"constant,omitempty"`
	Name                 string                                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Inputs               []*SmartContract_ABI_Entry_Param            `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*SmartContract_ABI_Entry_Param            `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Type                 SmartContract_ABI_Entry_EntryType           `protobuf:"varint,6,opt,name=type,proto3,enum=protocol.SmartContract_ABI_Entry_EntryType" json:"type,omitempty"`
	Payable              bool                                        `protobuf:"varint,7,opt,name=payable,proto3" json:"payable,omitempty"`
	StateMutability      SmartContract_ABI_Entry_StateMutabilityType `protobuf:"varint,8,opt,name=stateMutability,proto3,enum=protocol.SmartContract_ABI_Entry_StateMutabilityType" json:"stateMutability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *SmartContract_ABI_Entry) Reset()         { *m = SmartContract_ABI_Entry{} }
func (m *SmartContract_ABI_Entry) String() string { return proto.CompactTextString(m) }
func (*SmartContract_ABI_Entry) ProtoMessage()    {}
func (*SmartContract_ABI_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0, 0, 0}
}

func (m *SmartContract_ABI_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContract_ABI_Entry.Unmarshal(m, b)
}
func (m *SmartContract_ABI_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContract_ABI_Entry.Marshal(b, m, deterministic)
}
func (m *SmartContract_ABI_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContract_ABI_Entry.Merge(m, src)
}
func (m *SmartContract_ABI_Entry) XXX_Size() int {
	return xxx_messageInfo_SmartContract_ABI_Entry.Size(m)
}
func (m *SmartContract_ABI_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContract_ABI_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContract_ABI_Entry proto.InternalMessageInfo

func (m *SmartContract_ABI_Entry) GetAnonymous() bool {
	if m != nil {
		return m.Anonymous
	}
	return false
}

func (m *SmartContract_ABI_Entry) GetConstant() bool {
	if m != nil {
		return m.Constant
	}
	return false
}

func (m *SmartContract_ABI_Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartContract_ABI_Entry) GetInputs() []*SmartContract_ABI_Entry_Param {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SmartContract_ABI_Entry) GetOutputs() []*SmartContract_ABI_Entry_Param {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *SmartContract_ABI_Entry) GetType() SmartContract_ABI_Entry_EntryType {
	if m != nil {
		return m.Type
	}
	return SmartContract_ABI_Entry_UnknownEntryType
}

func (m *SmartContract_ABI_Entry) GetPayable() bool {
	if m != nil {
		return m.Payable
	}
	return false
}

func (m *SmartContract_ABI_Entry) GetStateMutability() SmartContract_ABI_Entry_StateMutabilityType {
	if m != nil {
		return m.StateMutability
	}
	return SmartContract_ABI_Entry_UnknownMutabilityType
}

type SmartContract_ABI_Entry_Param struct {
	Indexed              bool     `protobuf:"varint,1,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContract_ABI_Entry_Param) Reset()         { *m = SmartContract_ABI_Entry_Param{} }
func (m *SmartContract_ABI_Entry_Param) String() string { return proto.CompactTextString(m) }
func (*SmartContract_ABI_Entry_Param) ProtoMessage()    {}
func (*SmartContract_ABI_Entry_Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{0, 0, 0, 0}
}

func (m *SmartContract_ABI_Entry_Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContract_ABI_Entry_Param.Unmarshal(m, b)
}
func (m *SmartContract_ABI_Entry_Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContract_ABI_Entry_Param.Marshal(b, m, deterministic)
}
func (m *SmartContract_ABI_Entry_Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContract_ABI_Entry_Param.Merge(m, src)
}
func (m *SmartContract_ABI_Entry_Param) XXX_Size() int {
	return xxx_messageInfo_SmartContract_ABI_Entry_Param.Size(m)
}
func (m *SmartContract_ABI_Entry_Param) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContract_ABI_Entry_Param.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContract_ABI_Entry_Param proto.InternalMessageInfo

func (m *SmartContract_ABI_Entry_Param) GetIndexed() bool {
	if m != nil {
		return m.Indexed
	}
	return false
}

func (m *SmartContract_ABI_Entry_Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartContract_ABI_Entry_Param) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CreateSmartContract struct {
	OwnerAddress         []byte         `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	NewContract          *SmartContract `protobuf:"bytes,2,opt,name=new_contract,json=newContract,proto3" json:"new_contract,omitempty"`
	CallTokenValue       int64          `protobuf:"varint,3,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"`
	TokenId              int64          `protobuf:"varint,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateSmartContract) Reset()         { *m = CreateSmartContract{} }
func (m *CreateSmartContract) String() string { return proto.CompactTextString(m) }
func (*CreateSmartContract) ProtoMessage()    {}
func (*CreateSmartContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{1}
}

func (m *CreateSmartContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSmartContract.Unmarshal(m, b)
}
func (m *CreateSmartContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSmartContract.Marshal(b, m, deterministic)
}
func (m *CreateSmartContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSmartContract.Merge(m, src)
}
func (m *CreateSmartContract) XXX_Size() int {
	return xxx_messageInfo_CreateSmartContract.Size(m)
}
func (m *CreateSmartContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSmartContract.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSmartContract proto.InternalMessageInfo

func (m *CreateSmartContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *CreateSmartContract) GetNewContract() *SmartContract {
	if m != nil {
		return m.NewContract
	}
	return nil
}

func (m *CreateSmartContract) GetCallTokenValue() int64 {
	if m != nil {
		return m.CallTokenValue
	}
	return 0
}

func (m *CreateSmartContract) GetTokenId() int64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

type TriggerSmartContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress      []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CallValue            int64    `protobuf:"varint,3,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CallTokenValue       int64    `protobuf:"varint,5,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"`
	TokenId              int64    `protobuf:"varint,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerSmartContract) Reset()         { *m = TriggerSmartContract{} }
func (m *TriggerSmartContract) String() string { return proto.CompactTextString(m) }
func (*TriggerSmartContract) ProtoMessage()    {}
func (*TriggerSmartContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{2}
}

func (m *TriggerSmartContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerSmartContract.Unmarshal(m, b)
}
func (m *TriggerSmartContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerSmartContract.Marshal(b, m, deterministic)
}
func (m *TriggerSmartContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerSmartContract.Merge(m, src)
}
func (m *TriggerSmartContract) XXX_Size() int {
	return xxx_messageInfo_TriggerSmartContract.Size(m)
}
func (m *TriggerSmartContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerSmartContract.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerSmartContract proto.InternalMessageInfo

func (m *TriggerSmartContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TriggerSmartContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *TriggerSmartContract) GetCallValue() int64 {
	if m != nil {
		return m.CallValue
	}
	return 0
}

func (m *TriggerSmartContract) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TriggerSmartContract) GetCallTokenValue() int64 {
	if m != nil {
		return m.CallTokenValue
	}
	return 0
}

func (m *TriggerSmartContract) GetTokenId() int64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

type ClearABIContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress      []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearABIContract) Reset()         { *m = ClearABIContract{} }
func (m *ClearABIContract) String() string { return proto.CompactTextString(m) }
func (*ClearABIContract) ProtoMessage()    {}
func (*ClearABIContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{3}
}

func (m *ClearABIContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearABIContract.Unmarshal(m, b)
}
func (m *ClearABIContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearABIContract.Marshal(b, m, deterministic)
}
func (m *ClearABIContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearABIContract.Merge(m, src)
}
func (m *ClearABIContract) XXX_Size() int {
	return xxx_messageInfo_ClearABIContract.Size(m)
}
func (m *ClearABIContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearABIContract.DiscardUnknown(m)
}

var xxx_messageInfo_ClearABIContract proto.InternalMessageInfo

func (m *ClearABIContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ClearABIContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

type UpdateSettingContract struct {
	OwnerAddress               []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress            []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ConsumeUserResourcePercent int64    `protobuf:"varint,3,opt,name=consume_user_resource_percent,json=consumeUserResourcePercent,proto3" json:"consume_user_resource_percent,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *UpdateSettingContract) Reset()         { *m = UpdateSettingContract{} }
func (m *UpdateSettingContract) String() string { return proto.CompactTextString(m) }
func (*UpdateSettingContract) ProtoMessage()    {}
func (*UpdateSettingContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{4}
}

func (m *UpdateSettingContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSettingContract.Unmarshal(m, b)
}
func (m *UpdateSettingContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSettingContract.Marshal(b, m, deterministic)
}
func (m *UpdateSettingContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSettingContract.Merge(m, src)
}
func (m *UpdateSettingContract) XXX_Size() int {
	return xxx_messageInfo_UpdateSettingContract.Size(m)
}
func (m *UpdateSettingContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSettingContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSettingContract proto.InternalMessageInfo

func (m *UpdateSettingContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateSettingContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *UpdateSettingContract) GetConsumeUserResourcePercent() int64 {
	if m != nil {
		return m.ConsumeUserResourcePercent
	}
	return 0
}

type UpdateEnergyLimitContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress      []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	OriginEnergyLimit    int64    `protobuf:"varint,3,opt,name=origin_energy_limit,json=originEnergyLimit,proto3" json:"origin_energy_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEnergyLimitContract) Reset()         { *m = UpdateEnergyLimitContract{} }
func (m *UpdateEnergyLimitContract) String() string { return proto.CompactTextString(m) }
func (*UpdateEnergyLimitContract) ProtoMessage()    {}
func (*UpdateEnergyLimitContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_494f94e10ba63181, []int{5}
}

func (m *UpdateEnergyLimitContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEnergyLimitContract.Unmarshal(m, b)
}
func (m *UpdateEnergyLimitContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEnergyLimitContract.Marshal(b, m, deterministic)
}
func (m *UpdateEnergyLimitContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEnergyLimitContract.Merge(m, src)
}
func (m *UpdateEnergyLimitContract) XXX_Size() int {
	return xxx_messageInfo_UpdateEnergyLimitContract.Size(m)
}
func (m *UpdateEnergyLimitContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEnergyLimitContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEnergyLimitContract proto.InternalMessageInfo

func (m *UpdateEnergyLimitContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateEnergyLimitContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *UpdateEnergyLimitContract) GetOriginEnergyLimit() int64 {
	if m != nil {
		return m.OriginEnergyLimit
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.SmartContract_ABI_Entry_EntryType", SmartContract_ABI_Entry_EntryType_name, SmartContract_ABI_Entry_EntryType_value)
	proto.RegisterEnum("protocol.SmartContract_ABI_Entry_StateMutabilityType", SmartContract_ABI_Entry_StateMutabilityType_name, SmartContract_ABI_Entry_StateMutabilityType_value)
	proto.RegisterType((*SmartContract)(nil), "protocol.SmartContract")
	proto.RegisterType((*SmartContract_ABI)(nil), "protocol.SmartContract.ABI")
	proto.RegisterType((*SmartContract_ABI_Entry)(nil), "protocol.SmartContract.ABI.Entry")
	proto.RegisterType((*SmartContract_ABI_Entry_Param)(nil), "protocol.SmartContract.ABI.Entry.Param")
	proto.RegisterType((*CreateSmartContract)(nil), "protocol.CreateSmartContract")
	proto.RegisterType((*TriggerSmartContract)(nil), "protocol.TriggerSmartContract")
	proto.RegisterType((*ClearABIContract)(nil), "protocol.ClearABIContract")
	proto.RegisterType((*UpdateSettingContract)(nil), "protocol.UpdateSettingContract")
	proto.RegisterType((*UpdateEnergyLimitContract)(nil), "protocol.UpdateEnergyLimitContract")
}

func init() {
	proto.RegisterFile("core/contract/smart_contract.proto", fileDescriptor_494f94e10ba63181)
}

var fileDescriptor_494f94e10ba63181 = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0x3f, 0xd7, 0xf9, 0xe3, 0x4c, 0xda, 0xd4, 0x6c, 0xef, 0x84, 0x9b, 0xe3, 0xa4, 0x12, 0x84,
	0x2e, 0x08, 0xd5, 0x39, 0x82, 0xf8, 0x00, 0x5f, 0x4e, 0x69, 0x54, 0x44, 0x24, 0x40, 0x95, 0xaf,
	0x3d, 0x09, 0xbe, 0x58, 0x1b, 0x7b, 0x70, 0xad, 0x3a, 0xbb, 0xd6, 0x7a, 0x7d, 0x89, 0x9f, 0x05,
	0x89, 0x07, 0xe0, 0x15, 0x78, 0x17, 0x24, 0x5e, 0x80, 0x67, 0x40, 0xbb, 0xfe, 0x43, 0x53, 0x5d,
	0x89, 0x8a, 0xd4, 0x2f, 0xed, 0xce, 0x6f, 0x66, 0x76, 0x66, 0x7e, 0x53, 0xff, 0xb6, 0x30, 0x0a,
	0xb8, 0xc0, 0x49, 0xc0, 0x99, 0x14, 0x34, 0x90, 0x93, 0x6c, 0x45, 0x85, 0xf4, 0x6b, 0xd3, 0x4d,
	0x05, 0x97, 0x9c, 0x58, 0xfa, 0x57, 0xc0, 0x93, 0xe1, 0xa1, 0x8e, 0xbe, 0x14, 0x9c, 0x95, 0xae,
	0xd1, 0xdf, 0x16, 0x1c, 0xbc, 0x51, 0x39, 0xf3, 0x2a, 0x85, 0x7c, 0x0a, 0x03, 0x2e, 0xe2, 0x28,
	0x66, 0x3e, 0x0d, 0x43, 0x81, 0x59, 0xe6, 0x18, 0x27, 0xc6, 0x78, 0xdf, 0x3b, 0x28, 0xd1, 0x59,
	0x09, 0x92, 0xcf, 0xc0, 0xae, 0xab, 0x34, 0x81, 0x7b, 0x3a, 0xf0, 0xb0, 0xc6, 0xeb, 0xd0, 0x53,
	0x30, 0xe9, 0x32, 0x76, 0xcc, 0x13, 0x63, 0xdc, 0x9f, 0x3e, 0x77, 0xeb, 0x66, 0xdc, 0xad, 0xba,
	0xee, 0xec, 0x6c, 0xe1, 0xa9, 0x38, 0x32, 0x04, 0x6b, 0x59, 0x48, 0x0c, 0x78, 0x88, 0x4e, 0x4b,
	0xdf, 0xd8, 0xd8, 0xe4, 0x05, 0x40, 0x40, 0x93, 0xc4, 0x7f, 0x47, 0x93, 0x1c, 0x9d, 0xf6, 0x89,
	0x31, 0x36, 0xbd, 0x9e, 0x42, 0xde, 0x2a, 0x80, 0xcc, 0xe0, 0x45, 0xc0, 0x59, 0x96, 0xaf, 0xd0,
	0xcf, 0x33, 0x14, 0xbe, 0xc0, 0x8c, 0xe7, 0x22, 0x40, 0x3f, 0x45, 0x11, 0x20, 0x93, 0x4e, 0x47,
	0x67, 0x0c, 0xab, 0xa0, 0xab, 0x0c, 0x85, 0x57, 0x85, 0x5c, 0x94, 0x11, 0x84, 0x40, 0x8b, 0xd1,
	0x15, 0x3a, 0xdd, 0x13, 0x63, 0xdc, 0xf3, 0xf4, 0x99, 0xb8, 0x70, 0x54, 0x51, 0x82, 0x0c, 0x45,
	0x54, 0xf8, 0x49, 0xbc, 0x8a, 0xa5, 0x63, 0xe9, 0xcb, 0x3e, 0x28, 0x5d, 0xe7, 0xda, 0xf3, 0xbd,
	0x72, 0x90, 0xe7, 0xd0, 0x53, 0xdd, 0xfa, 0xd7, 0x34, 0xbb, 0x76, 0x7a, 0xe5, 0x08, 0x0a, 0xf8,
	0x8e, 0x66, 0xd7, 0xe4, 0x18, 0x2c, 0x29, 0x36, 0xa5, 0x0f, 0xb4, 0xaf, 0x2b, 0xc5, 0x46, 0xb9,
	0x86, 0x7f, 0xb5, 0xc1, 0x9c, 0x9d, 0x2d, 0xc8, 0xd7, 0xd0, 0x41, 0x26, 0x45, 0xa1, 0xa8, 0x37,
	0xc7, 0xfd, 0xe9, 0xc7, 0xff, 0xc1, 0x99, 0x7b, 0xae, 0x22, 0xbd, 0x2a, 0x61, 0xf8, 0x5b, 0x1b,
	0xda, 0x1a, 0x21, 0x1f, 0x41, 0x8f, 0x32, 0xce, 0x8a, 0x15, 0xcf, 0xcb, 0x15, 0x5a, 0xde, 0xbf,
	0x80, 0x22, 0x59, 0x91, 0x20, 0x29, 0x93, 0x7a, 0x6d, 0x96, 0xd7, 0xd8, 0x0d, 0x05, 0xe6, 0x2d,
	0x0a, 0x5e, 0x43, 0x27, 0x66, 0x69, 0x2e, 0x33, 0xa7, 0xa5, 0x5b, 0x7a, 0xb9, 0xb3, 0x25, 0xf7,
	0x82, 0x0a, 0xba, 0xf2, 0xaa, 0x34, 0x32, 0x83, 0x2e, 0xcf, 0xa5, 0xbe, 0xa1, 0xfd, 0xb0, 0x1b,
	0xea, 0x3c, 0xf2, 0x1a, 0x5a, 0xb2, 0x48, 0x51, 0x2f, 0x71, 0x30, 0xfd, 0x7c, 0x77, 0xbe, 0xfe,
	0x79, 0x59, 0xa4, 0xe8, 0xe9, 0x44, 0xe2, 0x40, 0x37, 0xa5, 0x05, 0x5d, 0x26, 0xe5, 0x7a, 0x2d,
	0xaf, 0x36, 0x89, 0x0f, 0x87, 0x99, 0xa4, 0x12, 0x7f, 0xc8, 0x25, 0x5d, 0xc6, 0x49, 0x2c, 0x0b,
	0xbd, 0xdd, 0xc1, 0xf4, 0xab, 0xdd, 0x55, 0xde, 0x6c, 0x27, 0xea, 0x7a, 0x77, 0x6f, 0x1b, 0x2e,
	0xa0, 0xad, 0xa7, 0x51, 0x3d, 0xc4, 0x2c, 0xc4, 0x0d, 0x86, 0xd5, 0x52, 0x6a, 0xb3, 0xa1, 0x7d,
	0xef, 0x16, 0xed, 0xa4, 0x1a, 0xb9, 0x5a, 0x85, 0x3a, 0x8f, 0x7e, 0x82, 0x5e, 0x33, 0x18, 0x79,
	0x0a, 0xf6, 0x15, 0xbb, 0x61, 0x7c, 0xcd, 0x1a, 0xcc, 0x7e, 0x42, 0x0e, 0xa1, 0x3f, 0x57, 0xdb,
	0x14, 0x79, 0x20, 0xb9, 0xb0, 0x0d, 0xb2, 0x0f, 0xd6, 0xb7, 0x39, 0x0b, 0x64, 0xcc, 0x99, 0xbd,
	0x47, 0x7a, 0xd0, 0x3e, 0x7f, 0x87, 0x4c, 0xda, 0xa6, 0x76, 0xd0, 0x24, 0x59, 0xd2, 0xe0, 0xc6,
	0x6e, 0x8d, 0x28, 0x1c, 0xbd, 0x67, 0x1a, 0x72, 0x0c, 0xcf, 0xaa, 0x22, 0xdb, 0x0e, 0xfb, 0x09,
	0xb1, 0xa0, 0x75, 0x91, 0x0b, 0xb4, 0x0d, 0x75, 0x7a, 0x1b, 0xe3, 0xda, 0xde, 0x23, 0x03, 0x80,
	0x1f, 0x39, 0xab, 0xa8, 0xb5, 0x4d, 0xd2, 0x87, 0xee, 0x45, 0x65, 0xb4, 0x46, 0x7f, 0x18, 0x70,
	0x34, 0x17, 0x48, 0x25, 0x6e, 0xcb, 0xce, 0x27, 0x70, 0xc0, 0xd7, 0x0c, 0xc5, 0x1d, 0xd5, 0xd9,
	0xd7, 0x60, 0xad, 0x24, 0xdf, 0xc0, 0x3e, 0xc3, 0x75, 0x23, 0x6f, 0x9a, 0xaa, 0xfe, 0xf4, 0xc3,
	0x7b, 0x76, 0xe4, 0xf5, 0x19, 0xae, 0x9b, 0x02, 0x63, 0xb0, 0xb5, 0x74, 0x48, 0x7e, 0x83, 0xac,
	0x12, 0x10, 0x53, 0x7f, 0xc1, 0x03, 0x85, 0x5f, 0x2a, 0xb8, 0x54, 0x11, 0xf5, 0x85, 0xea, 0xa0,
	0x38, 0xd4, 0x02, 0x64, 0x7a, 0x5d, 0x6d, 0x2f, 0xc2, 0xd1, 0x9f, 0x06, 0x3c, 0xbd, 0x14, 0x71,
	0x14, 0xa1, 0xf8, 0x1f, 0xed, 0x3f, 0x40, 0x33, 0xb7, 0x85, 0xce, 0xbc, 0x2b, 0x74, 0x04, 0x5a,
	0x21, 0x95, 0xb4, 0xd2, 0x47, 0x7d, 0x7e, 0xef, 0x80, 0xed, 0x9d, 0x03, 0x76, 0xb6, 0x07, 0x5c,
	0x82, 0x3d, 0x4f, 0x90, 0x8a, 0xd9, 0xd9, 0xe2, 0xb1, 0x66, 0x1b, 0xfd, 0x6e, 0xc0, 0xb3, 0xab,
	0x34, 0x54, 0x7f, 0x02, 0x28, 0x65, 0xcc, 0xa2, 0x47, 0x63, 0x71, 0xe7, 0x7b, 0x60, 0xee, 0x7a,
	0x0f, 0x46, 0xbf, 0x1a, 0x70, 0x5c, 0x36, 0x7b, 0x4b, 0xe1, 0x1f, 0xad, 0xe1, 0x7b, 0x5e, 0x1a,
	0xf3, 0x9e, 0x97, 0xe6, 0x6c, 0x0e, 0x0e, 0x17, 0x91, 0x2b, 0x9b, 0x07, 0x3d, 0x73, 0xeb, 0x2b,
	0x7f, 0x7e, 0x19, 0xc5, 0xf2, 0x3a, 0x5f, 0xba, 0x01, 0x5f, 0x4d, 0x5e, 0x6d, 0xbe, 0x78, 0xf5,
	0xcb, 0x44, 0x85, 0x9d, 0x46, 0x22, 0x0d, 0x4e, 0x23, 0x2a, 0x71, 0x4d, 0x8b, 0x89, 0xfa, 0x77,
	0x60, 0xd9, 0xd1, 0x99, 0x5f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x72, 0xc9, 0x12, 0x4b,
	0x08, 0x00, 0x00,
}
