// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/contract/storage_contract.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuyStorageBytesContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Bytes                int64    `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStorageBytesContract) Reset()         { *m = BuyStorageBytesContract{} }
func (m *BuyStorageBytesContract) String() string { return proto.CompactTextString(m) }
func (*BuyStorageBytesContract) ProtoMessage()    {}
func (*BuyStorageBytesContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb2d446a78170b16, []int{0}
}

func (m *BuyStorageBytesContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStorageBytesContract.Unmarshal(m, b)
}
func (m *BuyStorageBytesContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStorageBytesContract.Marshal(b, m, deterministic)
}
func (m *BuyStorageBytesContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStorageBytesContract.Merge(m, src)
}
func (m *BuyStorageBytesContract) XXX_Size() int {
	return xxx_messageInfo_BuyStorageBytesContract.Size(m)
}
func (m *BuyStorageBytesContract) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStorageBytesContract.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStorageBytesContract proto.InternalMessageInfo

func (m *BuyStorageBytesContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *BuyStorageBytesContract) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

type BuyStorageContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Quant                int64    `protobuf:"varint,2,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStorageContract) Reset()         { *m = BuyStorageContract{} }
func (m *BuyStorageContract) String() string { return proto.CompactTextString(m) }
func (*BuyStorageContract) ProtoMessage()    {}
func (*BuyStorageContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb2d446a78170b16, []int{1}
}

func (m *BuyStorageContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStorageContract.Unmarshal(m, b)
}
func (m *BuyStorageContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStorageContract.Marshal(b, m, deterministic)
}
func (m *BuyStorageContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStorageContract.Merge(m, src)
}
func (m *BuyStorageContract) XXX_Size() int {
	return xxx_messageInfo_BuyStorageContract.Size(m)
}
func (m *BuyStorageContract) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStorageContract.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStorageContract proto.InternalMessageInfo

func (m *BuyStorageContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *BuyStorageContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type SellStorageContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	StorageBytes         int64    `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellStorageContract) Reset()         { *m = SellStorageContract{} }
func (m *SellStorageContract) String() string { return proto.CompactTextString(m) }
func (*SellStorageContract) ProtoMessage()    {}
func (*SellStorageContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb2d446a78170b16, []int{2}
}

func (m *SellStorageContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellStorageContract.Unmarshal(m, b)
}
func (m *SellStorageContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellStorageContract.Marshal(b, m, deterministic)
}
func (m *SellStorageContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellStorageContract.Merge(m, src)
}
func (m *SellStorageContract) XXX_Size() int {
	return xxx_messageInfo_SellStorageContract.Size(m)
}
func (m *SellStorageContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SellStorageContract.DiscardUnknown(m)
}

var xxx_messageInfo_SellStorageContract proto.InternalMessageInfo

func (m *SellStorageContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *SellStorageContract) GetStorageBytes() int64 {
	if m != nil {
		return m.StorageBytes
	}
	return 0
}

type UpdateBrokerageContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Brokerage            int32    `protobuf:"varint,2,opt,name=brokerage,proto3" json:"brokerage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBrokerageContract) Reset()         { *m = UpdateBrokerageContract{} }
func (m *UpdateBrokerageContract) String() string { return proto.CompactTextString(m) }
func (*UpdateBrokerageContract) ProtoMessage()    {}
func (*UpdateBrokerageContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb2d446a78170b16, []int{3}
}

func (m *UpdateBrokerageContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBrokerageContract.Unmarshal(m, b)
}
func (m *UpdateBrokerageContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBrokerageContract.Marshal(b, m, deterministic)
}
func (m *UpdateBrokerageContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBrokerageContract.Merge(m, src)
}
func (m *UpdateBrokerageContract) XXX_Size() int {
	return xxx_messageInfo_UpdateBrokerageContract.Size(m)
}
func (m *UpdateBrokerageContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBrokerageContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBrokerageContract proto.InternalMessageInfo

func (m *UpdateBrokerageContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateBrokerageContract) GetBrokerage() int32 {
	if m != nil {
		return m.Brokerage
	}
	return 0
}

func init() {
	proto.RegisterType((*BuyStorageBytesContract)(nil), "protocol.BuyStorageBytesContract")
	proto.RegisterType((*BuyStorageContract)(nil), "protocol.BuyStorageContract")
	proto.RegisterType((*SellStorageContract)(nil), "protocol.SellStorageContract")
	proto.RegisterType((*UpdateBrokerageContract)(nil), "protocol.UpdateBrokerageContract")
}

func init() {
	proto.RegisterFile("core/contract/storage_contract.proto", fileDescriptor_fb2d446a78170b16)
}

var fileDescriptor_fb2d446a78170b16 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x52, 0xd1, 0x21, 0xbd, 0x44, 0xa1, 0x39, 0x78, 0x28, 0xa9, 0x60, 0x2f, 0xcd,
	0x56, 0xfc, 0x05, 0xa6, 0x3f, 0x40, 0x48, 0xf5, 0x22, 0x42, 0xd8, 0x6c, 0xd6, 0x55, 0x8c, 0x99,
	0x38, 0x3b, 0xa1, 0xe6, 0xdf, 0x4b, 0x36, 0x2e, 0xed, 0xb5, 0x9e, 0x96, 0x79, 0xbc, 0xf7, 0xcd,
	0xee, 0x3e, 0xb8, 0x51, 0x48, 0x5a, 0x28, 0x6c, 0x98, 0xa4, 0x62, 0x61, 0x19, 0x49, 0x1a, 0x5d,
	0x78, 0x21, 0x6d, 0x09, 0x19, 0xa3, 0x73, 0x77, 0x28, 0xac, 0x93, 0x27, 0x98, 0x65, 0x5d, 0xbf,
	0x1d, 0x6d, 0x59, 0xcf, 0xda, 0x6e, 0xfe, 0xac, 0xd1, 0x02, 0xa6, 0xb8, 0x6b, 0x34, 0x15, 0xb2,
	0xaa, 0x48, 0x5b, 0x1b, 0x07, 0xf3, 0x60, 0x19, 0xe6, 0xa1, 0x13, 0x1f, 0x46, 0x2d, 0xba, 0x82,
	0x49, 0x39, 0xa4, 0xe2, 0x93, 0x79, 0xb0, 0x3c, 0xcd, 0xc7, 0x21, 0x79, 0x84, 0x68, 0x4f, 0x3d,
	0x1a, 0xf8, 0xdd, 0xc9, 0x86, 0x3d, 0xd0, 0x0d, 0x49, 0x01, 0x97, 0x5b, 0x5d, 0xd7, 0xff, 0x22,
	0x2e, 0x60, 0xea, 0xbf, 0xe1, 0xf0, 0xaa, 0xa1, 0x3d, 0x78, 0x74, 0xf2, 0x0a, 0xb3, 0xe7, 0xb6,
	0x92, 0xac, 0x33, 0xc2, 0x4f, 0x7d, 0xfc, 0x92, 0x6b, 0xb8, 0x28, 0x7d, 0xd2, 0x2d, 0x98, 0xe4,
	0x7b, 0x21, 0xdb, 0x40, 0x8c, 0x64, 0x52, 0x26, 0x6c, 0xc6, 0x06, 0x6c, 0xea, 0x1b, 0x79, 0xb9,
	0x35, 0x1f, 0xfc, 0xde, 0x95, 0xa9, 0xc2, 0x2f, 0xb1, 0xfe, 0xb9, 0x5b, 0xbf, 0x89, 0xc1, 0xb6,
	0x32, 0xd4, 0xaa, 0x95, 0x91, 0xac, 0x77, 0xb2, 0x17, 0x43, 0xa9, 0xe5, 0x99, 0x4b, 0xde, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xba, 0xda, 0x46, 0x05, 0xe3, 0x01, 0x00, 0x00,
}
